
services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    networks:
      - web
      - demo  # Verbindung zu n8n-Netzwerk
    command:
      # API und Dashboard
      - --api.dashboard=true
      - --api.insecure=false  # SICHERHEIT: Dashboard nur über HTTPS
      
      # Provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      
      # SSL/TLS Security
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=mathis@avantera.de
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      
      # Enhanced Security Headers
      - --entrypoints.websecure.http.tls.options=modern@file
      
      # HTTP -> HTTPS Redirect (disabled for development)
      # - --entrypoints.web.http.redirections.entrypoint.to=websecure
      # - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # - --entrypoints.web.http.redirections.entrypoint.permanent=true
      
      # Logging für Monitoring
      - --log.level=INFO
      - --accesslog=true
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addServicesLabels=true
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl/letsencrypt:/letsencrypt
      - ./config/traefik-config:/etc/traefik/dynamic:ro  # Für erweiterte Konfiguration
      - ./services/traefik:/etc/traefik/dynamic:ro
      - ./config/auth:/config/auth:ro
    labels:
      # Traefik Dashboard mit Authentication
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`217.154.225.184`) && PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.tls=false"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=auth@file,secure-headers@docker"
      
      # Security Middleware
      - "traefik.http.middlewares.secure-headers.headers.framedeny=true"
      - "traefik.http.middlewares.secure-headers.headers.sslredirect=false"
      - "traefik.http.middlewares.secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
    
    # Flexible Ressourcen
    mem_limit: 512m        # Lightweight Proxy
    mem_reservation: 128m

networks:
  web:
    external: true
  demo:
    external: true

volumes:
  letsencrypt:
