# Users Database for AI Stack Authentication
# Default credentials: admin / admin123
# Change password after first login!

users:
  admin:
    displayname: "AI Stack Administrator"
    password: "$argon2id$v=19$m=65536,t=3,p=4$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t4MFFSs+iM"  # admin123
    email: admin@ai-stack.local
    groups:
      - admins
      - dev

groups:
  admins:
    - admin
  dev:
    - admin