_format_version: "1.1"

###
### Consumers / Users
###
consumers:
  - username: anon
    keyauth_credentials:
      - key: ${SUPABASE_ANON_KEY}
  - username: service_role
    keyauth_credentials:
      - key: ${SUPABASE_SERVICE_ROLE_KEY}

###
### Access Control List
###
acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

###
### API Routes
###
services:
  ## Open WebUI Integration
  - name: auth-v1-open
    url: http://supabase-auth:9999/
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - "/auth/v1/open"
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - Cache-Control
          exposed_headers:
            - Content-Length
            - Content-Type
            - X-Ratelimit-Limit
            - X-Ratelimit-Remaining
            - X-Ratelimit-Reset
          credentials: true
          max_age: 3600

  ## Main Auth API
  - name: auth-v1
    url: http://supabase-auth:9999/
    routes:
      - name: auth-v1-all
        strip_path: true
        paths:
          - "/auth/v1/"
    plugins:
      - name: cors
        config:
          origins:
            - "http://217.154.225.184:3000"
            - "http://217.154.225.184:3001"
            - "http://217.154.225.184:5678"
            - "http://217.154.225.184:6333"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - Cache-Control
            - X-Client-Info
            - apikey
          exposed_headers:
            - Content-Length
            - Content-Type
            - X-Ratelimit-Limit
            - X-Ratelimit-Remaining
            - X-Ratelimit-Reset
          credentials: true
          max_age: 3600

  ## PostgREST API
  - name: rest-v1
    url: http://supabase-rest:3000/
    routes:
      - name: rest-v1-all
        strip_path: true
        paths:
          - "/rest/v1/"
    plugins:
      - name: cors
        config:
          origins:
            - "http://217.154.225.184:3000"
            - "http://217.154.225.184:3001"
            - "http://217.154.225.184:5678"
            - "http://217.154.225.184:6333"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - Cache-Control
            - X-Client-Info
            - apikey
            - Prefer
            - Range
          exposed_headers:
            - Content-Length
            - Content-Type
            - Content-Range
            - X-Ratelimit-Limit
            - X-Ratelimit-Remaining
            - X-Ratelimit-Reset
          credentials: true
          max_age: 3600
      - name: rest-v1-rpc
        strip_path: true
        paths:
          - "/rest/v1/rpc/"

  ## Realtime API
  - name: realtime-v1
    url: http://supabase-realtime:4000/socket/
    routes:
      - name: realtime-v1-all
        strip_path: true
        paths:
          - "/realtime/v1/"
    plugins:
      - name: cors
        config:
          origins:
            - "http://217.154.225.184:3000"
            - "http://217.154.225.184:3001"
            - "http://217.154.225.184:5678"
            - "http://217.154.225.184:6333"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - Cache-Control
            - X-Client-Info
            - apikey
          credentials: true
          max_age: 3600

  ## Storage API
  - name: storage-v1
    url: http://supabase-storage:5000/
    routes:
      - name: storage-v1-all
        strip_path: true
        paths:
          - "/storage/v1/"
    plugins:
      - name: cors
        config:
          origins:
            - "http://217.154.225.184:3000"
            - "http://217.154.225.184:3001"
            - "http://217.154.225.184:5678"
            - "http://217.154.225.184:6333"
          methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Accept-Language
            - Content-Language
            - Content-Type
            - Authorization
            - Cache-Control
            - X-Client-Info
            - apikey
            - Range
          exposed_headers:
            - Content-Length
            - Content-Type
            - Content-Range
            - X-Ratelimit-Limit
            - X-Ratelimit-Remaining
            - X-Ratelimit-Reset
          credentials: true
          max_age: 3600

###
### API Key Authentication
###
plugins:
  - name: cors
    config:
      origins:
        - "https://loveable.dev"
        - "https://*.loveable.dev"
        - "http://localhost:3000"
        - "http://localhost:5173"
        - "https://avantera-digital.de"
        - "https://*.avantera-digital.de"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Language
        - Content-Language
        - Content-Type
        - Authorization
        - Cache-Control
        - X-Client-Info
        - apikey
        - Prefer
        - Range
      exposed_headers:
        - Content-Length
        - Content-Type
        - Content-Range
      credentials: true
      max_age: 3600
  - name: key-auth
    service: auth-v1
    config:
      key_names:
        - apikey
        - authorization
      key_in_body: false
      key_in_header: true
      key_in_query: true
      hide_credentials: false
  - name: key-auth
    service: rest-v1
    config:
      key_names:
        - apikey
        - authorization
      key_in_body: false
      key_in_header: true
      key_in_query: true
      hide_credentials: false
  - name: key-auth
    service: storage-v1
    config:
      key_names:
        - apikey
        - authorization
      key_in_body: false
      key_in_header: true
      key_in_query: true
      hide_credentials: false
  - name: key-auth
    service: realtime-v1
    config:
      key_names:
        - apikey
        - authorization
      key_in_body: false
      key_in_header: true
      key_in_query: true
      hide_credentials: false